---

- name: Download Android SDK tools
  get_url:
    url: "{{ android_sdk_download_location }}"
    dest: /tmp/sdk.zip
    validate_certs: no

- name: Extract Android SDK tools
  unarchive: src=/tmp/sdk.zip dest=/opt copy=no

- name: Set system wide PATH to contain Android SDK tools
  lineinfile: dest=/etc/environment regexp=^PATH line='PATH="/usr/local/sbin:/usr/local/bin:{{ android_sdk_install_location }}/platform-tools:{{ android_sdk_install_location }}/tools:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"'

- name: Set system wide ANDROID_HOME environment variable
  lineinfile: dest=/etc/environment regexp=^ANDROID_HOME line='ANDROID_HOME="{{ android_sdk_install_location }}"'

- name: Install platform and build tools
  shell: echo y | "{{ android_sdk_install_location }}"/tools/android update sdk --filter {{ item }} --no-ui -a --force
  with_items:
    - platform-tools
    - build-tools-23.0.0

- name: Install platforms
  shell: echo y | "{{ android_sdk_install_location }}"/tools/android update sdk --filter android-{{ item }} --no-ui -a --force
  with_items: "{{ android_sdk_versions }}"

- name: Install system images
  shell: echo y | "{{ android_sdk_install_location }}"/tools/android update sdk --filter sys-img-x86-android-{{ item }} --no-ui -a --force
  with_items: "{{ android_sdk_versions }}"

- name: Change permissions on SDK tools
  file: path={{ android_sdk_install_location }} recurse=yes mode=0755
